version: '3'
services:
  web:
    image:
      joaogmm/url-shortener-image:latest
    ports:
      - "5050:5050"
    depends_on:
      - mongo
  mongo:
    image: 
      mongo
    ports:
      - "27017:27017"